Ly_dailyfresh/Ly_dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # 全文搜索
    url(r'^search',include('haystack.urls')),
    # 配置富文本编辑框的url
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/',include('apps.user.urls',namespace='user')),
    url(r'^cart/',include('apps.cart.urls',namespace='cart')),
    url(r'^order/',include('apps.order.urls',namespace='order')),
    # 默认显示首页在商品模块中
    url(r'^',include('apps.goods.urls',namespace='goods')),

]

Ly_dailyfresh/apps/cart/urls.py
from django.conf.urls import url
from apps.cart.views import CartInfoView,CartInfoAdd, CartInfoUpdate,CartInfoDelete
urlpatterns = [
    # 添加到购物车
    url(r'^add$',CartInfoAdd.as_view(), name='add'),
    # 显示购物车页
    url(r'^$', CartInfoView.as_view(),name='show'),
    # 购物车数据更新
    url(r'^update$', CartInfoUpdate.as_view(), name='update'),
    # 删除购物车中的商品记录
    url(r'^delete$', CartInfoDelete.as_view(), name='delete'),
]

Ly_dailyfresh/apps/goods/urls.py
from django.conf.urls import url
from apps.goods.views import IndexView

# 登录装饰器
from django.contrib.auth.decorators import login_required
from apps.goods.views import DetailView, ListView

# /index
urlpatterns = [
    # 跳转到首页显示
    url(r'^index$', IndexView.as_view(),name='index'),
    url(r'^goods/(?P<sku_id>\d+)$', DetailView.as_view(), name='detail'), # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'), # 列表页

]

Ly_dailyfresh/apps/order/urls.py
from django.conf.urls import url
from  apps.order.views import OrderPlaceView,OrderCommitView

urlpatterns = [
    # 显示提交订单页面
    url(r'^place$', OrderPlaceView.as_view(), name='place'),
    # 订单提交
    url(r'^commit$', OrderCommitView.as_view(), name='commit'),

]

Ly_dailyfresh/apps/user/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.user.views import RegisterView, ActiveView, LoginView, LogoutView, UserInfoView, UserOrderView, AddressView

urlpatterns = [
    # url(r'^register$', register, name='register'), # 注册
    # url(r'^register_handle$', register_handle, name='register_handle'), # 注册处理

    url(r'^register$', RegisterView.as_view(), name='register'), # 注册
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'), # 激活

    url(r'^login$', LoginView.as_view(), name='login'), # 登录
    url(r'^logout$', LogoutView.as_view(), name='logout'), # 退出登录


    # 在url配置的时候，调用login_required装饰器，相当于配置的函数是login_required的返回值
    # url(r'^$', login_required(UserInfoView.as_view()), name='user'), # 用户中心-信息页
    # url(r'^order$', login_required(UserOrderView.as_view()), name='order'), # 用户中心-订单页
    # url(r'^address$', login_required(AddressView.as_view()), name='address'), # 用户中心-地址页

    url(r'^$', UserInfoView.as_view(), name='user'), # 用户中心-信息页
    url(r'^order$', UserOrderView.as_view(), name='order'), # 用户中心-订单页
    url(r'^address$', AddressView.as_view(), name='address'), # 用户中心-地址页

]

Ly_dailyfresh/apps/cart/models.py
from django.db import models

# Create your models here.

Ly_dailyfresh/apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from apps.goods.models import GoodsSKU
from django_redis import get_redis_connection

# Create your views here.
# 在前端使用ajax发起请求， 获取数据使用get方式，涉及到数据的修改使用post方式

# 在这使用post方式
class CartInfoAdd(View):
    '''添加购物车'''
    def post(self, request):
        # 获取user对象，判断用户是否已经登陆

        user = request.user

        if not user.is_authenticated():
            # 用户没有登陆,返回json
            return JsonResponse({'res':0, 'errmsg':'用户没有登陆'})

        # 用户已经登陆，开始接受参数
        sku_id = request.POST['sku_id']
        count = request.POST['count']
        # 参数校验
        if not all([sku_id, count ]):
            return JsonResponse({'res':1, 'errmsg':'参数不完整'})


        # 开始校验商品的id
        try:

            sku = GoodsSKU.objects.get(id = sku_id)
        except Exception as e :
            # 商品不存在
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 校验商品的数目
        try:
            count = int(count)
        except Exception as e:
            # 商品数目不是一个数字
            return JsonResponse({'res': 3, 'errmsg': '商品数目不合法'})

        if count <= 0:
            return JsonResponse({'res': 3, 'errmsg': '商品数目不合法'})

        # 业务处理：添加购物车记录 cart_1: {'1':2, '2':3}
        # sku_id已经被添加过，商品数目做累加, 否则加一个新的元素
        # 获取reids的连接，保存记录到redis
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 先获取sku_id的值
        cart_count = conn.hget(cart_key, sku_id)

        if cart_count:
            # redis中存在该商品，进行数量累加
            count += int(cart_count)
        # 判断商品的库存
        if count > sku.stock:
            # 库存不足
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
        # 库存数量足够，开始添加数据

        conn.hset(cart_key,sku_id, count)

        # 获取用户购物车中的条目数
        cart_count = conn.hlen(cart_key)

        # 返回json数据回前台界面
        return JsonResponse({'res':5, 'cart_count':cart_count, 'message':'添加成功'})


class CartInfoView(View):
    """购物车页面显示"""
    def get(self, request):
        """显示页面"""
        # 获取登陆的用户
        user = request.user
        # 连接redis
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_dict = conn.hgetall(cart_key)

        # 定义一个商品的空列表
        skus = []
        # 定义总价和总数量
        total_count = 0
        total_price = 0

        # 获取对应的商品信息,redis中的值是字符串类型
        for sku_id, count  in cart_dict.items():
            # 根据sku_id 获取商品信息
            sku = GoodsSKU.objects.get(id=sku_id)
            count = int(count)
            # 计算商品的小计
            amount = sku.price * count
            # 给商品动态的添加小计和数量
            sku.count = count
            sku.amount = amount

            # 将商品信息添加到列表中
            skus.append(sku)

            # 累计总的商品数量和总价
            total_price += amount
            total_count += count


        # 组织上下文
        context = {
            'skus': skus,
            'total_price': total_price,
            'total_count': total_count,
        }

        return render(request,'cart.html', context)


class CartInfoUpdate(View):
    """购物车的更新数据，使用ajax请求"""
    def post(self, request):

        # 获取用户数据
        user = request.user

        # 判断用户是否已经登录
        if not user.is_authenticated():
            # 用户未登录
            return JsonResponse({'res':0, 'errmsg': '用户未登录'})
        # 获取参数
        print(user)
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        print(sku_id, count)
        # 校验数据完整性
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg':'数据不完整'})

        # 检验是不是数字
        try:
            count = int(count)
        except Exception:
            return JsonResponse({'res':2, 'errmsg':'输入的非法字符'})

        # 检验商品id是否存在
        sku = GoodsSKU.objects.get(id=sku_id)
        if not sku:
            return JsonResponse({'res':3, 'errmsg': '商品不存在'})
        print('ajax 进入函数3')
        # 校验商品的库存数量
        if count > sku.stock:
            return JsonResponse({'res':4, 'errmsg':'商品库存不足'})

        # 开始进行业务逻辑处理，重新设置购物车中商品数量
        conn = get_redis_connection('default')
        # 构造cart_key
        cart_key = 'cart_%d' % user.id
        conn.hset(cart_key, sku_id, count)
        print('ajax 进入函数4')
        # 重新计算商品的总数量,拿到所有的商品数量
        total_count = 0
        hvals = conn.hvals(cart_key)

        # 遍历列表
        for val in hvals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res':5, 'total_count':total_count, 'message':'购物车更新成功'})


class CartInfoDelete(View):
    """删除购物车中商品记录，ajax 请求 post"""
    def post(self,request):
        # 判断用户是否已经登录
        user = request.user
        if not user:
            return JsonResponse({'res':0, 'errmsg':'用户未登录'})

        # 获取参数
        sku_id = request.POST.get('sku_id')
        # 校验参数
        if not sku_id:
            return JsonResponse({'res':1, 'errmsg':'数据不完整'})

        # 校验商品是否存在
        sku = GoodsSKU.objects.get(id = sku_id)
        if not sku:
            return JsonResponse({'res':2, 'errmsg':'商品的id不存在'})

        # 开始处理业务逻辑
        # 1.构建cart_key
        cart_key = 'cart_%d' % user.id
        # 2.连接redis，删除指定商品的记录
        conn = get_redis_connection('default')
        conn.hdel(cart_key, sku_id)

        # 重新计算购物车中商品的总数量
        hvals = conn.hvals(cart_key)
        # 遍历列表，数量累加，hash值是string类型，需要转化类型
        total_count = 0
        for val in hvals:
            total_count += int(val)

        # 处理完成，返回应答
        return  JsonResponse({'res':3, 'total_count':total_count, 'message':'删除商品记录完成'})

Ly_dailyfresh/templates/base.html
{# 登录 注册 首页 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部引入文件块 #}
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>

{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{# 网页搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">

            </form>

		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网页主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

Ly_dailyfresh/templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{# 网页主体内容块 #}
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class = "{{ type.logo }}">{{ type.name}}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页 列表页 主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

Ly_dailyfresh/templates/base_no_cart.html
{# 购物车页面 提交订单页面 #}
{% extends 'base.html' %}
{% load staticfiles %}
{# 网页搜索框块 #}
{% block search_bar %}

	<div class="search_bar clearfix">

		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
            <form action="/search" method="get">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>
{% endblock search_bar %}

Ly_dailyfresh/templates/base_user_center.html
{# 用户中心-3个页面 #}
{% extends 'base_no_cart.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'addr' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {# 用户中心-右侧内容块 #}
		{% block right_content %}{% endblock right_content %}
	</div>
{% endblock body %}

Ly_dailyfresh/templates/detail.html
{% extends 'base_detail_list.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-商品详情{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ sku.type.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
            <div>
                <div>其他规格:</div>
                <div>
                    {% for sku in same_spu_skus %}
                        <a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a>
                    {% endfor %}
                </div>
            </div>
			<div class="total">总价：<em>{{ sku.price }}元</em></div>
            {% csrf_token %}
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart"  sku_id="{{ sku.id }}"  id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.goods.detail|safe }}</dd>
				</dl>
			</div>

            <div class="tab_content" style="display: none;">
				<dl>
                    {% for order_sku in order_skus %}
                        <dt>评论时间: {{ order_sku.update_time }} 用户名:{{ order_sku.order.user.username }}</dt>
                        <dd>评论内容: {{ order_sku.comment }}</dd>
                    {% empty %}
                        暂时没有评论信息
                    {% endfor %}
				</dl>
			</div>

		</div>
	</div>
{% endblock main_content %}
{% block bottom %}
	<div class="add_jump"></div>
{% endblock bottom %}
{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
       // 计算商品的小计
        function update_sku_amount() {
            count = $('.num_show').val();
            price = $('.show_pirze').children('em').text();
            // 计算小计
            amount = parseFloat(price) * parseInt(count);
            // 设置商品的小计
            $('.total').children('em').text(amount.toFixed(2)+'元');

        }
       // 商品数量增加
        $('.add').click(function () {
            // 获取商品的数量
            count = $('.num_show').val();
            // 增加1
            count = parseInt(count)+1;
            // 重新设置商品的数量
            $('.num_show').val(count);

            // 重新计算小计
            update_sku_amount()

        });
        // 商品数量减少
       $('.minus').click(function () {
           count = $('.num_show').val();
           count = parseInt(count)-1;
           if (count <= 0) {
               count = 1;
           }
           $('.num_show').val(count);

           update_sku_amount();
       });
       // 手动输入
       $('.num_show').blur(function () {
           count = $(this).val();
           // 校验count 是否合法
           if (isNaN(count) || count.trim().length == 0 || parseInt(count)<=0){
                count = 1;
           }
           $('.num_show').val(parseInt(count));
           update_sku_amount();
       });

		// 获取add_cart a标签左上角的坐标
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

        // 获取show_count div元素左上角的坐标
		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

			$('#add_cart').click(function(){
            // 获取商品id和商品数目
            count = $('.num_show').val()
            sku_id = $(this).attr('sku_id') // prop attr
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf}
            // 发起ajax post请求，访问/cart/add, 传递参数:sku_id count
            $.post('{% url 'cart:add' %}', params, function (data) {
                if (data.res == 5){
                    // 添加成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                    'left': $to_y+7,
                    'top': $to_x+7},
                    "fast", function() {
                        $(".add_jump").fadeOut('fast',function(){
                            // 重新设置用户购物车中商品的条目数
                            $('#show_count').html(data.cart_count);
                        });
			        });
                }
                else{
                    alert(data.errmsg)
                }
            })

		})
	</script>
{% endblock bottomfiles %}

Ly_dailyfresh/templates/static_base.html
<<<<<<< HEAD
{# 登录 注册 首页显示 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	{# 网页标题块 #}
    <title>{% block title  %}天天生鲜-首页{% endblock title %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
</head>

<body>
{# 网页顶部欢迎模块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
            {# 判断用户是否已经登录，显示用户的信息,当前登陆的用户信息会封装到user对象中，使用is_authenticvated函数的值进行判断 #}

                <div class="login_btn fl">
                    <a href="{% url 'user:login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'user:register' %}">注册</a>
                </div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_con %}

{# 网页搜索模块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
{% endblock search_bar %}
{# 网页主体的内容 #}
{% block body %}{% endblock body%}

{# 网页的底部内容 #}
    <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
    </div>

{# 网页底部的HTML块 #}
{% block bottom %}{% endblock bottom %}

{# 网页底部的引入文件块 #}
{% block bottomfiles %}{% endblock bottomfiles %}

</body>
=======
{# 登录 注册 首页 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部引入文件块 #}
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>

{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{# 网页搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网页主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
>>>>>>> dev
</html>